- hosts: ec2
  become: yes
  tasks:
    - name: webserver is installed 
      package: 
        name: nginx
        state: present
    - name: webserver is running
      service:
        name: nginx
        state: started


