- hosts: ec2
  become: yes
  vars: 
    webserver: nginx
    webserver_root_dir: /var/www/html
    tasks:
    - name: webserver is installed 
      package: 
        name: "{{ webserver }}"
        state: present
    - name: webserver is running
      service:
        name: "{{ webserver }}"
        state: started
    - name: web server root directory created 
      file:
        path: "{{ webserver_root_dir }}"
        state: directory
    - name: static website 
      uri:
        url: https://raw.githubusercontent.com/abdennour/example-static-website/ansible-course/login.html
        dest: "{{ webserver_root_dir }}" # /usr/share/nginx/html


