- hosts: ec2
  become: yes
  tasks:
  - name: weserver is installed
    package:
      name: nginx
      state: present
    register: nginx_install_output
  - name: print in terminal
    debug:
      var: nginx_install_output
  - name: copy to output
    copy:
      content: "{{ nginx_install_output }}"
      dest: /tmp/task-1.txt

