- name: delegate task to local hosts
 hosts: dev1
 tasks:
  - name: string is copied into file
    copy: 
      content: This is a message while targeting {{ inventory_hostname }}
      dest: /tmp/message.txt
    delegate_to: localhost
    